openapi: 3.0.3
info:
  version: 1.0.0
  title: Sample App
servers:
  - url: https://example.com/
paths:
  /users:
    get:
      parameters:
        - name: role
          in: query
          required: true
          schema:
            type: string
            enum: [ admin, maintainer ]
        - name: minimum
          in: query
          required: false
          schema:
            type: integer
        - name: maximum
          in: query
          required: false
          schema:
            type: integer
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                - name: role
                  required: true
                  schema:
                    type: string
                    enum: [ admin, maintainer ]
  /users/{user_id}:
    get:
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: integer
  /users/{user_id}/articles:
    get:
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: integer
  /users/{user_id}/articles/{article_id}:
    get:
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: integer
        - name: article_id
          in: path
          required: true
          schema:
            type: integer
